version: '3'
services:

    mysql:
        image: mysql:8.0
        container_name: db-look-back-list
        command:
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
            - --sql-mode=ONLY_FULL_GROUP_BY,NO_ENGINE_SUBSTITUTION
        environment:
            MYSQL_ROOT_USER: ${ROOTUSER}
            MYSQL_ROOT_PASSWORD: ${ROOTUSER}
            MYSQL_DATABASE: ${DATABASE}
            MYSQL_USER: ${USERNAME}
            MYSQL_PASSWORD: ${USERPASS}
            TZ: 'Asia/Tokyo'
        ports:
            - "3306:3306"
        volumes:
            - db-volume:/var/lib/mysql

volumes:
    db-volume:
